name: Trigger remote deploy

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger remote workflow
        run: |
          curl -X POST https://api.github.com/repos/SoundsGreaat/server-configuration/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" \
            -d '{"event_type":"deploy"}'
